# This setup tests ICF-related software and workflows. There are two elements
# that have to be kept aligned with ICF's environment:
#
# 1. The input data structure should match the data that ICF receives from
#    acquisition sides.
#
# 2. The software environment should match the environment on ICF's machines,
#    i.e. the versions of: `git`, `git-annex`, `python`, `datalad`, and
#    `datalad-next`.


# This version of Ubuntu is based on debian bullseye
image: Ubuntu2004


environment:
  # Set this to `after-install` to activate the ssh login after the
  # install-steps are executed.
  # Set it to 'pre-tests' to activate ssh login just before the tests are
  # executed.
  # This requires setting `APPVEYOR_SSH_KEY` and `APPVEYOR_SSH_BLOCK`
  ACTIVATE_SSH_LOGIN: no

  # The git-annex deb-package we want to use
  GIT_ANNEX_DEB: http://snapshot.debian.org/archive/debian/20210906T204127Z/pool/main/g/git-annex/git-annex_8.20210903-1_amd64.deb

  # The root for study data and the studies that we simulate. These variables
  # are available throughout ``install:´´ and in the executed scripts.
  FROM_SCANNER: /data/incoming
  STUDIES_DIR: /data/archive
  STUDIES: "study_1 study_2"

install:
  # Bootstrap ICF-like system installation
  - sudo .appveyor/install_apt_pkgs
  - .appveyor/apache_enable_user_dir
  # Install a sufficiently recent git annex version
  - .appveyor/install_git_annex $GIT_ANNEX_DEB
  # Install tooling for data ingestion.
  # ICF uses a system installation via APT. Here we only match the respective
  # versions of Debian bullseye (the Ubuntu 2004 base image is too old)
  - sudo python3 -m pip install pydicom==2.0.0 tqdm==4.57.0

  # Bootstrap ICF data organization
  # Create data input directory and populate it
  - sudo mkdir -p "$FROM_SCANNER"
  - sh:
      for s in $STUDIES; do
        .appveyor/data_create_scanner_output $FROM_SCANNER $s 10 20;
      done
  # Create study directories
  - sh:
      for s in $STUDIES; do
        sudo mkdir -p "$STUDIES_DIR"/$s;
      done
  # Create user http content and create links to the studies in. The http server
  # is configured to follow only links if the owner of the link matches the
  # owner of the target. Therefore, user ``root´´ has to create the links.
  - mkdir ~/public_html
  - sh:
      for s in $STUDIES; do
        sudo ln -s "$STUDIES_DIR"/$s /home/appveyor/public_html/$s;
      done
  # Enable basic authentication and authorization for the study directories. The
  # username is ``test.user´´, the password is ``secret_1´´.
  - sh:
      .appveyor/apache_enable_authentication
        $STUDIES_DIR
        test.user secret_1
        $STUDIES

  # Run the non-DataLad DICOM data ingestion script
  - sh:
      for s in $STUDIES; do
        sudo bin/make_studyvisit_archive
          --output-dir "$STUDIES_DIR"
          --id $s visit_1
          "$FROM_SCANNER";
      done

  # Enable external SSH access to CI worker on all other systems. This uses the
  # public key defined in APPVEYOR_SSH_KEY. If APPVEYOR_SSH_BLOCK is ``true´´,
  # the worker waits with the continuation of the build beyond this point until
  # the file ``~/build.lock´´ is removed.
  - sh:
      if [ X"$ACTIVATE_SSH_LOGIN" == "Xafter-install" ]; then
        curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -;
      fi


# Disable automatic builds with MSBuild, we use custom build steps instead.
build: off


# We use a generic python3 command to invoke the standard python version of
# debian "bullseye". Nevertheless, let's create a virtual environment to keep
# things separated.
build_script:
  # Set up git identification
  - git config --global user.email "test@appveyor.land"
  - git config --global user.name "Appveyor Almighty"
  # Enable "next" extension for patching datalad core
  - git config --global datalad.extensions.load next

  - . ~/venv3.7/bin/activate
  - python --version
  # Install requirements
  - python -m pip install -r requirements-devel.txt
  # Install the latest version from pypi, even if it is a development or beta version
  - python -m pip install --pre datalad-next


before_test:
  - . ~/venv3.7/bin/activate
  - python --version
  # simple call to see if datalad and git-annex are installed properly
  - datalad wtf


test_script:
  # run tests found in the $PROJECT_ROOT/test directory
  - mkdir __testhome__
  - cd __testhome__
  - which python
  - python --version
  - env
  - sh:
      if [ X"$ACTIVATE_SSH_LOGIN" == "Xpre-tests" ]; then
        curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -;
      fi
  - python -m pytest -s -v ../tests
