# This setup tests ICF-related software and workflows. There are two elements
# that have to be kept aligned with ICF's environment:
#
# 1. The input data structure should match the data that ICF receives from
#    acquisition sides.
#
# 2. The software environment should match the environment on ICF's machines,
#    i.e. the versions of: `git`, `git-annex`, `python`, `datalad`, and
#    `datalad-next`.


# This version of Ubuntu is based on debian bullseye
image: Ubuntu


environment:
  # Those are currently used to engineer the test VM. They will be removed,
  # once the test VM is complete.
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0ou94Vnrz7iClYApJWv9FVOjT8uDgaF4Uf6wRW2VzLWD4/YwtxD5tsri9SfyQXFwVs94H0EAZSUz06VSM7uQwtOyeoHhERCfx0u+GC1UaFPLi20+4x7GLwipKLRWaf6dHfO5R4LkgDxH9Lc2KbzD0JYB7Lt4Hk54TWd1RaLuM0JGJCJc/0z5uQsyf6iH3Rf2Rcueoa61ztyjBwHaTJT8NOOtBATJXupN5c7Ss63hM7NecMdsalkLCnKQ3CwXQ8Wyp6w3XKvTlymJaWZBxBlA8MzVv89z9oReYnbWDzfWvNn4JU9JDcyOxTec/hd58vRZ+Pz1ZFU6WipoJ0gb0GBu/
  APPVEYOR_SSH_BLOCK: true


install:
  # Install apache and enable user-dir serving
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install apache2
  - sh: .appveyor/apache_enable_user_dir

  # The root for study data and the studies that we simulate
  - sh: DATA_DIR=/var/www/data
  - sh: STUDIES="study_1 study_2"

  # Create study directories
  - sh: <
      for s in $STUDIES;
        do sudo mkdir -p "$DATA_DIR"/$s;
      done

  # Create user http content and create links to the studies in. The http server
  # is configured to follow only links if the owner of the link matches the
  # owner of the target. Therefore, user ``root´´ has to create the links.
  - sh: mkdir ~/public_html
  - sh: <
      for s in $STUDIES; do
        sudo ln -s "$DATA_DIR"/$s /home/appveyor/public_html/$s;
      done

  # Enable basic authentication and authorization for the study directories. The
  # username is ``test.user´´, the password is ``secret_1´´.
  - sh: .appveyor/apache_enable_authentication test.user secret_1 $STUDIES

  # Enable external SSH access to CI worker on all other systems. This uses the
  # public key defined in APPVEYOR_SSH_KEY. If APPVEYOR_SSH_BLOCK is ``true´´,
  # the worker waits with the continuation of the build beyond this point until
  # the file ``~/build.lock´´ is removed.
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


# Disable automatic builds with MSBuild, we use custom build steps instead.
build: off
